title: 3D Object Detection Hub
baseurl: ""
url: ""

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

scholar:
  style:        apa
  locale:       en
  bibliography: "references.bib"
  