# _config.yml
title: 3D Object Detection Hub
email: your-email@example.com
description: >-
  A comprehensive resource aggregating benchmarks, methods and results
  from my master thesis and the broader 3D object detection community.
baseurl: ""      # e.g. "/3d-hub" if hosted in a sub-folder
url: ""          # e.g. "https://example.com"
twitter_username: yourtwitter
github_username: yourgithub

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude build artifacts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
