title: 3D Object Detection Hub
baseurl: ""   # keep empty if serving from user/org pages root or gh-pages root
url: "https://3d-object-detection-hub.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

scholar:
  style: apa
  locale: en
  source: _bibliography
  bibliography: references.bib
