title: "3D Object Detection Hub"
description: "Benchmarks, methods, and datasets for monocular and multi-modal 3D object detection"
theme: just-the-docs

color_scheme: dark

url: https://elpatoo.github.io

# Enable the search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Show page navigation on the sidebar
nav_sort: case_insensitive

# Set repo if you want a "View on GitHub" link
repository: elpatoo/elpatoo.github.io
