name: build & deploy site

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repo
      - uses: actions/checkout@v3

      # 2) Set up Ruby & install gems
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8        # match your local ruby
          bundler-cache: true

      # 3) Build the Jekyll site
      - name: Bundle install & build
        run: |
          bundle exec jekyll build \
            --config _config.yml \
            --future       # if you use `site.time`

      # 4) Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
