name: Build & Deploy Jekyll site

# whenever you push to main (or adjust to your default branch)
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up the exact Ruby version you use locally
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'     # ← match your local `ruby -v`
          bundler-cache: true     # caches ~/.bundle between runs

      # 3. Install dependencies from your Gemfile
      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      # 4. Build the site with *your* plugins (including jekyll-scholar)
      - name: Build site with Jekyll
        run: bundle exec jekyll build --verbose

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
