# .github/workflows/ci.yml
name: Build site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # match your local Ruby version

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: bundle exec jekyll build --future --verbose

      # optionally, you can add steps here to deploy to GitHub Pages, S3, etc.
