name: Build & Deploy Site

on:
  push:
    branches: [ master ]     # or `master` if your default branch is named that
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out repo
      - uses: actions/checkout@v3

      # 2) Set up Ruby & cache your gems
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8        # match your local Ruby
          bundler-cache: true

      # 3) Install & build with your Gemfile (so jekyll-scholar loads)
      - name: Install gems & build site
        run: |
          bundle install
          bundle exec jekyll build \
            --config _config.yml \
            --future           # only if you use `site.time`

      # 4) Push the resulting _site/ to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:    ${{ secrets.GITHUB_TOKEN }}
          publish_dir:     ./_site
