# .github/workflows/deploy.yml
name: build & deploy site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v4

      # 2. Set up Ruby & cache gems
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
          bundler-cache: true

      # 3. Install your Gemfile gems (including jekyll-scholar)
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      # 4. Build with Jekyll (loads jekyll-scholar!)
      - name: Build with Jekyll
        run: bundle exec jekyll build --future

      # 5. Deploy the generated _site folder to gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
